# Generated by Django 4.0.5 on 2022-06-18 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_address', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=50)),
                ('address_state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burgerwars.address')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_nameCard', models.CharField(max_length=100)),
                ('payment_cardNum', models.DecimalField(decimal_places=0, max_digits=16)),
                ('payment_ccv', models.DecimalField(decimal_places=0, max_digits=3)),
                ('payment_expMonth', models.CharField(max_length=20)),
                ('payment_expDay', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_description', models.TextField()),
                ('product_image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burgerwars.cart')),
                ('item_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burgerwars.product')),
                ('topping_item', models.ManyToManyField(to='burgerwars.topping')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burgerwars.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burgerwars.payment'),
        ),
    ]
