# Generated by Django 4.0.5 on 2022-06-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgerwars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_toppings',
            field=models.ManyToManyField(to='burgerwars.topping'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
