# Generated by Django 4.0.5 on 2022-06-26 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burgerwars', '0002_product_product_toppings_product_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='topping_item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_toppings',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
